### ISSUE TITLE
SetPixels32 called with invalid number of pixels in the array UnityEngine.Texture2D:SetPixels32

### ISSUE THREAD

**Issue by ashleyjamesbrown** [nickdu088/unityqrscanner#2]
SetPixels32 called with invalid number of pixels in the array
UnityEngine.Texture2D:SetPixels32 (UnityEngine.Color32[])
QRScanner/<GetQRCode>d__3:MoveNext () (at Assets/Assets/Scripts/QRScanner.cs:30)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

Any ideas to resolve this

Unity 2019.4.21

**Comment by ashleyjamesbrown** [comment]
Realised this is because i was scanning a normal barcode. Any ideas how to make this work for a normal 2d code?

**Comment by nickdu088** [comment]
Which Unity version are you using? I tested on 2019 and 2018, and both are working well.

**Comment by nickdu088** [comment]
> SetPixels32 called with invalid number of pixels in the array
> UnityEngine.Texture2D:SetPixels32 (UnityEngine.Color32[])
> QRScanner/d__3:MoveNext () (at Assets/Assets/Scripts/QRScanner.cs:30)
> UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)
> 
> Any ideas to resolve this
> 
> Unity 2019.4.21

Which Unity version are you using? I tested on 2019 and 2018, and both are working well.

**Comment by nickdu088** [comment]
> SetPixels32 called with invalid number of pixels in the array
> UnityEngine.Texture2D:SetPixels32 (UnityEngine.Color32[])
> QRScanner/d__3:MoveNext () (at Assets/Assets/Scripts/QRScanner.cs:30)
> UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)
> 
> Any ideas to resolve this
> 
> Unity 2019.4.21

I tested on Unity 2019.4.x, and it works. 
According to https://docs.unity3d.com/2019.4/Documentation/ScriptReference/Texture2D.SetPixels32.html
and https://docs.unity3d.com/2019.4/Documentation/ScriptReference/WebCamTexture.GetPixels32.html
Texture2D should accept Color32[], which returns from WebCamTexture.

If not, you can try the this:

   Color32[] colors =new Color32[webcamTexture.width * webcamTexture.height]; ;
   webcamTexture.GetPixels32(colors);
   // or colors =  webcamTexture.GetPixels32();
   snap.SetPixels32(colors);

**Comment by ashleyjamesbrown** [comment]
The QR worked but normal 2d barcodes do not.
I get the error.

**Comment by nickdu088** [comment]
> The QR worked but normal 2d barcodes do not.
> I get the error.

Oh! I use zxing library to decode the barcode.

This line will return the decoding result
`var Result = barCodeReader.Decode(snap.GetRawTextureData(), webcamTexture.width, webcamTexture.height, RGBLuminanceSource.BitmapFormat.ARGB32);`

You can try to change the parameter of xing library to see if it works.

You can test your 2d barcode here https://zxing.org/w/decode.jspx first.
If it works, you can update the zxing library in plugin folder with the latest version.

According to https://www.nuget.org/packages/ZXing.Net/
zxing should support both 1d and 2d barcode.
>ZXing.Net is a port of ZXing, an open-source, multi-format 1D/2D barcode image processing library originally implemented in Java.

**Comment by ashleyjamesbrown** [comment]
Yeh thats the line i was looking at. 

Ive also got the plugin in the folder, not sure its the latest one its the one from your github :-) Ill see if theres a newer one.

Im just scanning everyday household objects so it should work

**Comment by nickdu088** [comment]
> Yeh thats the line i was looking at.
> 
> Ive also got the plugin in the folder, not sure its the latest one its the one from your github :-) Ill see if theres a newer one.
> 
> Im just scanning everyday household objects so it should work

The one you found in the plugin folder is 0.16.5. It shouldn't make big difference.

**Comment by ashleyjamesbrown** [comment]
Then i have no idea why it wont scan ANY 2d barcodes and gives the error regardless. ;-/

**Comment by ashleyjamesbrown** [comment]
https://zxing.org/w/decode. worked when i took a photo of the barcode and uploaded it.

Running it in Unity. Nothing but the error.

**Comment by ashleyjamesbrown** [comment]
Just to confirm - _im still only checking in the Editor_ rather than a Build. (i dont know why it would matter but im going to do an Android build and test it as well.)

**Comment by nickdu088** [comment]
> Just to confirm - _im still only checking in the Editor_ rather than a Build. (i dont know why it would matter but im going to do an Android build and test it as well.)

it doesn't matter.
check this out.
https://github.com/micjahn/ZXing.Net/issues/162#issuecomment-442981708

I use default settings in this project:
`IBarcodeReader barCodeReader = new BarcodeReader();`

You can add additional settings something like this: 
```
IBarcodeReader barCodeReader = new BarcodeReader()
{
    AutoRotate = true,
    TryInverted = true,
    Options = new DecodingOptions()
    {
        TryHarder = true,
	PossibleFormats = new List<BarcodeFormat>()
	{
	    BarcodeFormat.QR_CODE,
	    BarcodeFormat.UPC_A,
	    BarcodeFormat.UPC_E,
	    BarcodeFormat.EAN_8,
	    BarcodeFormat.EAN_13,
	    BarcodeFormat.CODE_39,
	    BarcodeFormat.CODE_93,
	    BarcodeFormat.CODE_128,
	    BarcodeFormat.CODABAR,
	    BarcodeFormat.ITF,
	    BarcodeFormat.RSS_14,
	    BarcodeFormat.PDF_417,
	    BarcodeFormat.RSS_EXPANDED,
	    BarcodeFormat.DATA_MATRIX
	}
    }
};
```
