### ISSUE TITLE
Webcam gets rotated on android devices

### ISSUE THREAD

**Issue by aadi3124** [nickdu088/unityqrscanner#3]
Hi, On editor its working fine, but on android devices, the webcam gets rotated. Please check and update.

**Comment by nickdu088** [comment]
You can mirror or rotate the RawImage in scene editor, rebuild and deploy on Android device.

**Comment by aadi3124** [comment]
Thanks! Did that and it's working now.
Want to ask one more thing, will this plugin work for ios too?

**Comment by nickdu088** [comment]
Yes. But you need Mac and xcode to rebuild.

**Comment by aadi3124** [comment]
Hi, Thanks for the reply,
Yes, I am building it on Mac and in xcode, but it's working on the iOS devices, Are there any specific changes that need to be done for the iOS?

**Comment by nickdu088** [comment]
I don't quite understand your question. You said "you build on Mac and xcode, but it's working on the iOS device" If it's working on iOS devices, what's your question?

**Comment by aadi3124** [comment]
Sorry for the writing mistake, "not" is missing in that, actually it is
I am building it on Mac and in xcode, but it's not working on the iOS devices.
The camera is on but it is not scanning the QR code

**Comment by nickdu088** [comment]
Did you follow the instructions here?
https://docs.unity3d.com/Manual/UnityCloudBuildiOS.html
Maybe some permission you didn't set on.

https://answers.unity.com/questions/1687742/how-to-check-camera-permission-in-ios-app.html
also https://developer.apple.com/documentation/arkit/verifying_device_support_and_user_permission

**Comment by aadi3124** [comment]
Hi, 
I followed all the Unity xcode build instructions and also given camera permission. My build is working fine on ios phone. Camera permission is okay and working fine **but not scanning the QR code**, this is the only issue. On android everything working fine. I am stuck here. Please help!

**Comment by nickdu088** [comment]
That could be ZXing library issue. You can try to debug to see if ZXing can read the bar code or not.
Or even replace my ZXing library with any other 3rd party .net QR library.
https://www.google.com/search?q=.+net+qr+library
