### ISSUE TITLE
It is not working on iPad. Does it support also iPad?

### ISSUE THREAD

**Issue by ghost** [nickdu088/unityqrscanner#6]
I have tried that package on Android Devices. It works very well, but after XCode build and trying on my iPad, camera is running but nothing detected when I put it on QR code.

**Comment by nickdu088** [comment]
It should work. Unity is cross platform. check the permissions or some other settings.

**Comment by t-janssen** [comment]
i'm also experiencing the same issue. Android works perfect but on IOS we get nothing but the camera view.

**Comment by nickdu088** [comment]
according to https://github.com/micjahn/ZXing.Net
it supports ios. I updated the zxing.net to 0.16.8, and hope it works for ios.

**Comment by QuantuDev** [comment]
Check if textures have matching size, on my iPad WebCamTexture has 16x16 and after some time it changes to the final resolution (it can be a little different than the requested one). 
So in while loop you need to add code checking if snap texture is same resolution as WebCamTexture and if not, resize it.

**Comment by nickdu088** [comment]
> Check if textures have matching size, on my iPad WebCamTexture has 16x16 and after some time it changes to the final resolution (it can be a little different than the requested one). So in while loop you need to add code checking if snap texture is same resolution as WebCamTexture and if not, resize it.

Can you confirm if it is working on iPad?

**Comment by QuantuDev** [comment]
Yes, it's working.

**Comment by nickdu088** [comment]
> Check if textures have matching size, on my iPad WebCamTexture has 16x16 and after some time it changes to the final resolution (it can be a little different than the requested one). So in while loop you need to add code checking if snap texture is same resolution as WebCamTexture and if not, resize it.



> Yes, it's working.

The WebCamTexture  is pre-defined as 512x512.
https://github.com/nickdu088/Unity-QR-Scanner/blob/master/Assets/Scripts/QRScanner.cs#L16

You can change to any you like.
